### PR TITLE
feat: middleware changes

### PR DESCRIPTION
**Pull request by sichanyoo**
## Issue \#

https://github.com/awslabs/aws-sdk-swift/issues/1145

## Description of changes

Adds auth scheme signing properties customization hook to SigV4AuthScheme.

Accompanying PR: https://github.com/smithy-lang/smithy-swift/pull/605

## Conventional Commits

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jbelkins — CHANGES_REQUESTED** [review]
Like the corresponding smithy-swift PR, there should be unit tests for the logic added here

**Review by jbelkins — APPROVED** [review]
Approved with the understanding that unit tests will be added later:
https://github.com/awslabs/aws-sdk-swift/issues/1148

**Review by dayaffe — APPROVED** [review]
Nit: I would prefer if this function had more comments to make it more readable.

**Pull request merged**
