### PR TITLE
feat: add visionOS support to useragent

### PR DESCRIPTION
**Pull request by dayaffe**
## Conventional Commits

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jbelkins — APPROVED** [review]
Approved.  I did file this issue as a followup:
https://github.com/awslabs/aws-sdk-swift/issues/1183

**Comment by jbelkins** [comment]
> Approved. I did file this issue as a followup: #1183

Seems this PR already does the user-agent part of this issue.  We do need to update our internal docs though.

**Comment by dayaffe** [comment]
Related issue: https://github.com/smithy-lang/smithy-swift/issues/603

**Pull request merged**
