### PR TITLE
chore: Enable all services

### PR DESCRIPTION
**Pull request by jbelkins**
## Issue \#
https://github.com/awslabs/aws-sdk-swift/issues/1047

## Description of changes
Re-enables code generation of all AWS services.

(also: disables the Swiftlint `trailing_comma` rule)

## New/existing dependencies impact assessment, if applicable
No new dependencies were added to this change.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jbelkins** [comment]
This is currently blocked and should not merge until https://github.com/awslabs/smithy-swift/pull/566 has merged.

**Review by waahm7 — APPROVED** [review]

**Comment by jbelkins** [comment]
https://github.com/awslabs/smithy-swift/pull/566 has merged, so this is no longer blocked.

**Pull request merged**
